//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedDetailsImageVisualizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeedDetailsImageVisualizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DylogSplashReportTool {
            get {
                object obj = ResourceManager.GetObject("DylogSplashReportTool", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00,q
        ///01,w
        ///02,e
        ///03,r
        ///04,t
        ///05,y
        ///06,u
        ///07,i
        ///08,o
        ///09,p
        ///010,a
        ///011,s
        ///012,d
        ///013,f
        ///014,g
        ///015,h
        ///016,j
        ///017,k
        ///018,l
        ///019,z
        ///020,x
        ///021,c
        ///022,v
        ///023,b
        ///024,n
        ///025,m
        ///026,,
        ///027,:
        ///028, 
        ///029,;
        ///030,.
        ///
        ///00,Q
        ///01,W
        ///02,E
        ///03,R
        ///04,T
        ///05,Y
        ///06,U
        ///07,I
        ///08,O
        ///09,P
        ///010,A
        ///011,S
        ///012,D
        ///013,F
        ///014,G
        ///015,H
        ///016,J
        ///017,K
        ///018,L
        ///019,Z
        ///020,X
        ///021,C
        ///022,V
        ///023,B
        ///024,N
        ///025,M
        ///026,,
        ///027,:
        ///028, 
        ///029,;
        ///030,.
        ///
        ///00,\
        ///01,|
        ///02,!
        ///03,&quot;
        ///04,$
        ///05,%
        ///06,&amp;
        ///07,/
        ///08,(
        ///09,)
        ///010,=
        ///011,&apos;
        ///012,?
        ///013,[
        ///014,]        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KeyboardEnglishLayout {
            get {
                return ResourceManager.GetString("KeyboardEnglishLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
