//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ResourceManager.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.ResourceManager.Cultures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the images folder.
        /// </summary>
        public static string Caption_Select_The_Images_Folder {
            get {
                return ResourceManager.GetString("Caption_Select_The_Images_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:.
        /// </summary>
        public static string Label_Action {
            get {
                return ResourceManager.GetString("Label_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Label_Add {
            get {
                return ResourceManager.GetString("Label_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional:.
        /// </summary>
        public static string Label_Additional {
            get {
                return ResourceManager.GetString("Label_Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANY.
        /// </summary>
        public static string Label_Any {
            get {
                return ResourceManager.GetString("Label_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Label_Apply {
            get {
                return ResourceManager.GetString("Label_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Label_Back {
            get {
                return ResourceManager.GetString("Label_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause:.
        /// </summary>
        public static string Label_Cause {
            get {
                return ResourceManager.GetString("Label_Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Label_Clear {
            get {
                return ResourceManager.GetString("Label_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Label_Comments {
            get {
                return ResourceManager.GetString("Label_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Label_Confirm {
            get {
                return ResourceManager.GetString("Label_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Label_Connecting {
            get {
                return ResourceManager.GetString("Label_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string Label_Create_Report {
            get {
                return ResourceManager.GetString("Label_Create_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a shortcut.
        /// </summary>
        public static string Label_Create_Shortcut {
            get {
                return ResourceManager.GetString("Label_Create_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to network image folder.
        /// </summary>
        public static string Label_Credential_Connection {
            get {
                return ResourceManager.GetString("Label_Credential_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and Time:.
        /// </summary>
        public static string Label_Date_Time {
            get {
                return ResourceManager.GetString("Label_Date_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Label_Disabled {
            get {
                return ResourceManager.GetString("Label_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Label_Domain {
            get {
                return ResourceManager.GetString("Label_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Label_Enabled {
            get {
                return ResourceManager.GetString("Label_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENGLISH.
        /// </summary>
        public static string Label_English {
            get {
                return ResourceManager.GetString("Label_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXIT.
        /// </summary>
        public static string Label_Exit {
            get {
                return ResourceManager.GetString("Label_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        public static string Label_File_Name {
            get {
                return ResourceManager.GetString("Label_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string Label_FileName {
            get {
                return ResourceManager.GetString("Label_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Label_Filter {
            get {
                return ResourceManager.GetString("Label_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters:.
        /// </summary>
        public static string Label_Filters {
            get {
                return ResourceManager.GetString("Label_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILTERS.
        /// </summary>
        public static string Label_Filters_Title {
            get {
                return ResourceManager.GetString("Label_Filters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Label_Find {
            get {
                return ResourceManager.GetString("Label_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FRENCH.
        /// </summary>
        public static string Label_France {
            get {
                return ResourceManager.GetString("Label_France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource shortcut.
        /// </summary>
        public static string Label_Friendly_Name {
            get {
                return ResourceManager.GetString("Label_Friendly_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string Label_From_Date {
            get {
                return ResourceManager.GetString("Label_From_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string Label_Go_To {
            get {
                return ResourceManager.GetString("Label_Go_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Subtitle.
        /// </summary>
        public static string Label_Image_Subtitle {
            get {
                return ResourceManager.GetString("Label_Image_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images:.
        /// </summary>
        public static string Label_Images {
            get {
                return ResourceManager.GetString("Label_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Label_Images_Title {
            get {
                return ResourceManager.GetString("Label_Images_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAGE SIZE.
        /// </summary>
        public static string Label_Imagine {
            get {
                return ResourceManager.GetString("Label_Imagine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the net credentials.
        /// </summary>
        public static string Label_Insert_Credentials {
            get {
                return ResourceManager.GetString("Label_Insert_Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITALY.
        /// </summary>
        public static string Label_Italy {
            get {
                return ResourceManager.GetString("Label_Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Language {
            get {
                return ResourceManager.GetString("Label_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading images...
        /// </summary>
        public static string Label_Loading_Images {
            get {
                return ResourceManager.GetString("Label_Loading_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Label_Logo {
            get {
                return ResourceManager.GetString("Label_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODIFY.
        /// </summary>
        public static string Label_Modify {
            get {
                return ResourceManager.GetString("Label_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Label_No {
            get {
                return ResourceManager.GetString("Label_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° article:.
        /// </summary>
        public static string Label_Number_Article {
            get {
                return ResourceManager.GetString("Label_Number_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° lot:.
        /// </summary>
        public static string Label_Number_Lot {
            get {
                return ResourceManager.GetString("Label_Number_Lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° images:.
        /// </summary>
        public static string Label_Number_Of_Images {
            get {
                return ResourceManager.GetString("Label_Number_Of_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Label_OK {
            get {
                return ResourceManager.GetString("Label_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open report after created.
        /// </summary>
        public static string Label_Open_Report_After_Created {
            get {
                return ResourceManager.GetString("Label_Open_Report_After_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Label_Options {
            get {
                return ResourceManager.GetString("Label_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Label_Page {
            get {
                return ResourceManager.GetString("Label_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages:.
        /// </summary>
        public static string Label_Pages {
            get {
                return ResourceManager.GetString("Label_Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Label_Path {
            get {
                return ResourceManager.GetString("Label_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Date:.
        /// </summary>
        public static string Label_Reject_Time {
            get {
                return ResourceManager.GetString("Label_Reject_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        public static string Label_Remove {
            get {
                return ResourceManager.GetString("Label_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Label_Report {
            get {
                return ResourceManager.GetString("Label_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Label_Reset {
            get {
                return ResourceManager.GetString("Label_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Label_Retry {
            get {
                return ResourceManager.GetString("Label_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Label_Rotation {
            get {
                return ResourceManager.GetString("Label_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save credentials.
        /// </summary>
        public static string Label_Save_credentials {
            get {
                return ResourceManager.GetString("Label_Save_credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save in.
        /// </summary>
        public static string Label_Save_In {
            get {
                return ResourceManager.GetString("Label_Save_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT.
        /// </summary>
        public static string Label_Select {
            get {
                return ResourceManager.GetString("Label_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Report destination.
        /// </summary>
        public static string Label_Select_Report_Destination {
            get {
                return ResourceManager.GetString("Label_Select_Report_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Path.
        /// </summary>
        public static string Label_SharedFolder {
            get {
                return ResourceManager.GetString("Label_SharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string Label_Subtitle {
            get {
                return ResourceManager.GetString("Label_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_Title {
            get {
                return ResourceManager.GetString("Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Label_Title_Filters {
            get {
                return ResourceManager.GetString("Label_Title_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Label_Title_Page {
            get {
                return ResourceManager.GetString("Label_Title_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string Label_To_Date {
            get {
                return ResourceManager.GetString("Label_To_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        public static string Label_Up {
            get {
                return ResourceManager.GetString("Label_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USA.
        /// </summary>
        public static string Label_USA {
            get {
                return ResourceManager.GetString("Label_USA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Label_Warning {
            get {
                return ResourceManager.GetString("Label_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Label_Yes {
            get {
                return ResourceManager.GetString("Label_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the specificated path.
        /// </summary>
        public static string Message_Can_Not_Open_Folder {
            get {
                return ResourceManager.GetString("Message_Can_Not_Open_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating report.
        /// </summary>
        public static string Message_Creating_Report {
            get {
                return ResourceManager.GetString("Message_Creating_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Report is not created: {0}.
        /// </summary>
        public static string Message_Creating_Report_Error {
            get {
                return ResourceManager.GetString("Message_Creating_Report_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path is not specified.
        /// </summary>
        public static string Message_Empty_Path {
            get {
                return ResourceManager.GetString("Message_Empty_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        public static string MESSAGE_ERROR_ACCESS_DENIED {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account is currently locked out..
        /// </summary>
        public static string MESSAGE_ERROR_ACCOUNT_LOCKED_OUT {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_ACCOUNT_LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network name cannot be found..
        /// </summary>
        public static string MESSAGE_ERROR_BAD_NET_NAME {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_BAD_NET_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified username is invalid..
        /// </summary>
        public static string Message_Error_Bad_Username {
            get {
                return ResourceManager.GetString("Message_Error_Bad_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the domain controller for this domain..
        /// </summary>
        public static string MESSAGE_ERROR_DOMAIN_CONTROLLER_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_DOMAIN_CONTROLLER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified network password is not correct..
        /// </summary>
        public static string Message_Error_Invalid_Password {
            get {
                return ResourceManager.GetString("Message_Error_Invalid_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon failure: unknown user name or bad password..
        /// </summary>
        public static string Message_Error_Logon {
            get {
                return ResourceManager.GetString("Message_Error_Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system cannot open the specified path. Try to check the credentials.
        /// </summary>
        public static string MESSAGE_ERROR_PATH_NOT_FOUND {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR_PATH_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is broken. A new file will be created with defualt values..
        /// </summary>
        public static string Message_File_Corrupted {
            get {
                return ResourceManager.GetString("Message_File_Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;{0}&quot; is broken or missing. The application can not start. Create a new &quot;{0}&quot; file and try again.
        /// </summary>
        public static string Message_File_Missing_OR_Corrupted {
            get {
                return ResourceManager.GetString("Message_File_Missing_OR_Corrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters not applied! Press ENTER on a text box to apply them..
        /// </summary>
        public static string Message_Filter_Applied {
            get {
                return ResourceManager.GetString("Message_Filter_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters not applied! Press ENTER on a text box to apply them..
        /// </summary>
        public static string Message_Filter_Not_Applied {
            get {
                return ResourceManager.GetString("Message_Filter_Not_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images not found with applied filters.
        /// </summary>
        public static string Message_Image_Not_Found_With_Applied_Filter {
            get {
                return ResourceManager.GetString("Message_Image_Not_Found_With_Applied_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files not found in {0}. Check the Folder or the Images options.
        /// </summary>
        public static string Message_Images_Files_Not_Found {
            get {
                return ResourceManager.GetString("Message_Images_Files_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images not found.
        /// </summary>
        public static string Message_Images_Not_Found {
            get {
                return ResourceManager.GetString("Message_Images_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple connections to a server or shared resource by the same user, using more than one user name, are not allowed. Disconnect all previous connections to the server or shared resource and try again.
        /// </summary>
        public static string Message_Multiple_Connection {
            get {
                return ResourceManager.GetString("Message_Multiple_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filters applied. Click the icon to set the filters..
        /// </summary>
        public static string Message_No_Filters_Applied {
            get {
                return ResourceManager.GetString("Message_No_Filters_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modfy the filters.
        /// </summary>
        public static string Message_Open_Filter {
            get {
                return ResourceManager.GetString("Message_Open_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Path &apos;{0}&apos; does not exist!.
        /// </summary>
        public static string Message_Path_Not_Exists {
            get {
                return ResourceManager.GetString("Message_Path_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Report was successfully created.
        /// </summary>
        public static string Message_Report_Created_Successfully {
            get {
                return ResourceManager.GetString("Message_Report_Created_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will be created {0} reports each with a maximum of 1000 images.
        /// </summary>
        public static string Message_Reports_Partioned {
            get {
                return ResourceManager.GetString("Message_Reports_Partioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to reset the filters.
        /// </summary>
        public static string Message_Reset_Filter {
            get {
                return ResourceManager.GetString("Message_Reset_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to lose all the changes?.
        /// </summary>
        public static string Message_Reset_Modified_Parameters {
            get {
                return ResourceManager.GetString("Message_Reset_Modified_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save updated parameters?.
        /// </summary>
        public static string Message_Save_Modified_Parameters {
            get {
                return ResourceManager.GetString("Message_Save_Modified_Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string Message_Unknown_Error {
            get {
                return ResourceManager.GetString("Message_Unknown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: {0}.
        /// </summary>
        public static string Message_Warning {
            get {
                return ResourceManager.GetString("Message_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving in defualt path..
        /// </summary>
        public static string Message_Warning_Path_Not_Exists {
            get {
                return ResourceManager.GetString("Message_Warning_Path_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network path was not found..
        /// </summary>
        public static string Messager_Error_Bad_Netpath {
            get {
                return ResourceManager.GetString("Messager_Error_Bad_Netpath", resourceCulture);
            }
        }
    }
}
